import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { deflateSync } from 'node:zlib';

const css = await readFile(new URL('../content/gate.css', import.meta.url), 'utf8');
await writeFile(new URL('../content/gate-style.js', import.meta.url), `// Generated by npm run assets from content/gate.css. Checked in for build-free installation.\nglobalThis.HAKI_GATE_CSS = ${JSON.stringify(css)};\n`);

// A geometric H, drawn as a vector-like pixel mask at 4x and downsampled. No image dependencies.
function crc32(bytes) {
  let crc = 0xffffffff;
  for (const byte of bytes) {
    crc ^= byte;
    for (let bit = 0; bit < 8; bit++) crc = (crc >>> 1) ^ ((crc & 1) ? 0xedb88320 : 0);
  }
  return (crc ^ 0xffffffff) >>> 0;
}
function chunk(type, bytes) {
  const name = Buffer.from(type), length = Buffer.alloc(4), checksum = Buffer.alloc(4);
  length.writeUInt32BE(bytes.length); checksum.writeUInt32BE(crc32(Buffer.concat([name, bytes])));
  return Buffer.concat([length, name, bytes, checksum]);
}
await mkdir(new URL('../assets/', import.meta.url), { recursive: true });
for (const size of [16, 32, 48, 128]) {
  const pixels = Buffer.alloc((size * 4 + 1) * size);
  for (let y = 0; y < size; y++) for (let x = 0; x < size; x++) {
    let coverage = 0;
    for (let sy = 0; sy < 4; sy++) for (let sx = 0; sx < 4; sx++) {
      const py = (y + sy / 4) / size, px = (x + sx / 4) / size + (py - .5) * .12;
      if ((py >= .22 && py <= .78) && ((px >= .22 && px <= .35) || (px >= .65 && px <= .78) || (py >= .445 && py <= .555 && px >= .3 && px <= .7))) coverage++;
    }
    const ratio = coverage / 16, offset = y * (size * 4 + 1) + 1 + x * 4;
    [4, 11, 19].forEach((bg, i) => { pixels[offset + i] = Math.round(bg + ([57, 186, 255][i] - bg) * ratio); });
    pixels[offset + 3] = 255;
  }
  const header = Buffer.alloc(13); header.writeUInt32BE(size); header.writeUInt32BE(size, 4); header[8] = 8; header[9] = 6;
  const png = Buffer.concat([Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]), chunk('IHDR', header), chunk('IDAT', deflateSync(pixels)), chunk('IEND', Buffer.alloc(0))]);
  await writeFile(new URL(`../assets/icon${size}.png`, import.meta.url), png);
}
console.log('Generated local gate styles and four Haki icons.');
