import { readFile, readdir, access } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import assert from 'node:assert/strict';
import { PLATFORM_MARKUP } from './site-platforms.mjs';

const manifest = JSON.parse(await readFile('manifest.json', 'utf8'));
assert.equal(manifest.manifest_version, 3);
assert.deepEqual(manifest.permissions, ['storage', 'scripting']);
assert.deepEqual(manifest.optional_host_permissions, ['https://*/*']);
assert.equal(manifest.host_permissions, undefined);
for (const path of [manifest.background.service_worker, manifest.action.default_popup, manifest.options_page, manifest.chrome_url_overrides.newtab, ...Object.values(manifest.icons)]) await access(path);
const runtime = ['background', 'content', 'shared', 'onboarding', 'options', 'popup', 'newtab', 'privacy'];
let count = 0;
for (const dir of runtime) for (const file of await readdir(dir)) {
  const path = `${dir}/${file}`;
  if (file.endsWith('.js')) {
    const result = spawnSync(process.execPath, ['--check', path], { encoding: 'utf8' });
    assert.equal(result.status, 0, result.stderr); count++;
    const source = await readFile(path, 'utf8');
    assert.doesNotMatch(source, /\beval\s*\(|\bnew Function\s*\(/, `${path}: dynamic code is forbidden`);
  }
  if (file.endsWith('.html')) {
    const html = await readFile(path, 'utf8');
    assert.doesNotMatch(html, /<script[^>]*src=["']https?:/i);
    assert.doesNotMatch(html, /\son[a-z]+\s*=/i);
    assert.match(html, /<html lang="en"/);
  }
}
const css = await readFile('content/gate.css', 'utf8');
assert.equal(await readFile('content/gate-style.js', 'utf8'), `// Generated by npm run assets from content/gate.css. Checked in for build-free installation.\nglobalThis.HAKI_GATE_CSS = ${JSON.stringify(css)};\n`, 'Run npm run assets after changing gate.css');
for (const size of [16, 32, 48, 128]) {
  const png = await readFile(`assets/icon${size}.png`);
  assert.equal(png.readUInt32BE(16), size); assert.equal(png.readUInt32BE(20), size);
}
assert.ok((await readFile('website/index.html', 'utf8')).includes(PLATFORM_MARKUP), 'Run npm run site:platforms to sync the landing-page catalog');
assert.equal(spawnSync(process.execPath, ['--check', 'website/site.js']).status, 0);
console.log(`Manifest, ${count} runtime scripts, local assets, CSP-compatible HTML and generated gate CSS passed.`);
